name: Build and Deploy
on:
  push:
    branches:
      - "master"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Setup Dependencies
        run: |
          pip install -r requirements.txt

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.34"
          install-modules: |
            Math::Round
            YAML

      - name: Test
        run: |
          python check.py

      - name: Build
        run: |
          python build.py

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          branch: gh-pages
          folder: build
